server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

paytabs:
  profile_id: 132344
  integration_key: SWJ992BZTN-JHGTJBWDLM-BZJKMR2ZHT
  instance: Egypt
  api_url: "https://secure-egypt.paytabs.com/payment/request"
